name: Enforce Rebasing

on: [push]

jobs:
  rebase_job:
    runs-on: ubuntu-latest
    name: Enforce rebasing

    steps:
    - name: Is Rebased on master?
      uses: jonahx/hello-world-javascript-action@v15
