name: Enforce Rebasing

on: [push]

jobs:
  rebase_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git checkout ${GITHUB_SHA}
    - name: Is Rebased on master?
      run: ./is_rebased
